-- MySQL Script generated by MySQL Workbench
-- Tue Apr 11 20:58:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema storemngsys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema storemngsys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `storemngsys` DEFAULT CHARACTER SET utf8 ;
USE `storemngsys` ;

-- -----------------------------------------------------
-- Table `storemngsys`.`sms_user_master`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `storemngsys`.`sms_user_master` (
  `userid` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `usertype` ENUM('ADMIN', 'CUSTOMER') NOT NULL,
  `mobilenumber` VARCHAR(10) NOT NULL,
  `shippingaddress` TINYTEXT NULL,
  `billingaddress` TINYTEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
